### ISSUE TITLE
More typos

### ISSUE THREAD

**Issue by sluugdemogithub** [edhowland/FizzBuzz_Challenge#2]
There are a few more typos in the readme file.

https://github.com/edhowland/FizzBuzz_Challenge/blob/main/README.md

**Comment by sluugdemogithub** [comment]
Typos in the readme file.

https://github.com/edhowland/FizzBuzz_Challenge/blob/main/README.md

**Comment by sluugdemogithub** [comment]
I'll tackle them. - Robert

**Comment by edhowland** [comment]
Ok, I saw no line that you wanted to remove any lines when I clicked on the link in the issue above.
Have you not actually forked it yet.

BTW, I assume this comment will generate an email back to whoever sluugdiscussgithub is.
And I got here via an email when this issue (#2) was opened.

Regards, Ed

**Comment by sluugdemogithub** [comment]
Yes, there is no pull request, yet. I only created an issue. And, yes, this
comment was emailed to me. And I’m replying using email instead of via the
browser.  - Robert

**Comment by rwcitek** [comment]
In contrast, this comment was created from the GitHub app. - Robert
